//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayZTradeCenter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DayZTradeCenter.Resources.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammunition.
        /// </summary>
        public static string ItemCategories_Ammunition {
            get {
                return ResourceManager.GetString("ItemCategories_Ammunition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string ItemCategories_Attachments {
            get {
                return ResourceManager.GetString("ItemCategories_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing.
        /// </summary>
        public static string ItemCategories_Clothing {
            get {
                return ResourceManager.GetString("ItemCategories_Clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string ItemCategories_Equipment {
            get {
                return ResourceManager.GetString("ItemCategories_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food and Drink.
        /// </summary>
        public static string ItemCategories_FoodAndDrink {
            get {
                return ResourceManager.GetString("ItemCategories_FoodAndDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazines.
        /// </summary>
        public static string ItemCategories_Magazines {
            get {
                return ResourceManager.GetString("ItemCategories_Magazines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical.
        /// </summary>
        public static string ItemCategories_Medical {
            get {
                return ResourceManager.GetString("ItemCategories_Medical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons.
        /// </summary>
        public static string ItemCategories_Weapons {
            get {
                return ResourceManager.GetString("ItemCategories_Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backpacks.
        /// </summary>
        public static string ItemSubcategories_Backpacks {
            get {
                return ResourceManager.GetString("ItemSubcategories_Backpacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandages.
        /// </summary>
        public static string ItemSubcategories_Bandages {
            get {
                return ResourceManager.GetString("ItemSubcategories_Bandages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayonets.
        /// </summary>
        public static string ItemSubcategories_Bayonets {
            get {
                return ResourceManager.GetString("ItemSubcategories_Bayonets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berries.
        /// </summary>
        public static string ItemSubcategories_Berries {
            get {
                return ResourceManager.GetString("ItemSubcategories_Berries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bipods.
        /// </summary>
        public static string ItemSubcategories_Bipods {
            get {
                return ResourceManager.GetString("ItemSubcategories_Bipods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bladed Melee.
        /// </summary>
        public static string ItemSubcategories_BladedMelee {
            get {
                return ResourceManager.GetString("ItemSubcategories_BladedMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Testing.
        /// </summary>
        public static string ItemSubcategories_BloodTesting {
            get {
                return ResourceManager.GetString("ItemSubcategories_BloodTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Transfusion.
        /// </summary>
        public static string ItemSubcategories_BloodTransfusion {
            get {
                return ResourceManager.GetString("ItemSubcategories_BloodTransfusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blunt Melee.
        /// </summary>
        public static string ItemSubcategories_BluntMelee {
            get {
                return ResourceManager.GetString("ItemSubcategories_BluntMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boots.
        /// </summary>
        public static string ItemSubcategories_Boots {
            get {
                return ResourceManager.GetString("ItemSubcategories_Boots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bows.
        /// </summary>
        public static string ItemSubcategories_Bows {
            get {
                return ResourceManager.GetString("ItemSubcategories_Bows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttstocks.
        /// </summary>
        public static string ItemSubcategories_Buttstocks {
            get {
                return ResourceManager.GetString("ItemSubcategories_Buttstocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canned Goods.
        /// </summary>
        public static string ItemSubcategories_CannedGoods {
            get {
                return ResourceManager.GetString("ItemSubcategories_CannedGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containers.
        /// </summary>
        public static string ItemSubcategories_Containers {
            get {
                return ResourceManager.GetString("ItemSubcategories_Containers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking.
        /// </summary>
        public static string ItemSubcategories_Cooking {
            get {
                return ResourceManager.GetString("ItemSubcategories_Cooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorational.
        /// </summary>
        public static string ItemSubcategories_Decorational {
            get {
                return ResourceManager.GetString("ItemSubcategories_Decorational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string ItemSubcategories_Devices {
            get {
                return ResourceManager.GetString("ItemSubcategories_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disinfection.
        /// </summary>
        public static string ItemSubcategories_Disinfection {
            get {
                return ResourceManager.GetString("ItemSubcategories_Disinfection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks.
        /// </summary>
        public static string ItemSubcategories_Drinks {
            get {
                return ResourceManager.GetString("ItemSubcategories_Drinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry Food.
        /// </summary>
        public static string ItemSubcategories_DryFood {
            get {
                return ResourceManager.GetString("ItemSubcategories_DryFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Weapons.
        /// </summary>
        public static string ItemSubcategories_ElectricWeapons {
            get {
                return ResourceManager.GetString("ItemSubcategories_ElectricWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyewear.
        /// </summary>
        public static string ItemSubcategories_Eyewear {
            get {
                return ResourceManager.GetString("ItemSubcategories_Eyewear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruits.
        /// </summary>
        public static string ItemSubcategories_Fruits {
            get {
                return ResourceManager.GetString("ItemSubcategories_Fruits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenades.
        /// </summary>
        public static string ItemSubcategories_Grenades {
            get {
                return ResourceManager.GetString("ItemSubcategories_Grenades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handguards.
        /// </summary>
        public static string ItemSubcategories_Handguards {
            get {
                return ResourceManager.GetString("ItemSubcategories_Handguards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handgun Ammunition.
        /// </summary>
        public static string ItemSubcategories_HandgunAmmunition {
            get {
                return ResourceManager.GetString("ItemSubcategories_HandgunAmmunition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handgun Magazines.
        /// </summary>
        public static string ItemSubcategories_HandgunMagazines {
            get {
                return ResourceManager.GetString("ItemSubcategories_HandgunMagazines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handguns.
        /// </summary>
        public static string ItemSubcategories_Handguns {
            get {
                return ResourceManager.GetString("ItemSubcategories_Handguns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands and Arms.
        /// </summary>
        public static string ItemSubcategories_HandsAndArms {
            get {
                return ResourceManager.GetString("ItemSubcategories_HandsAndArms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hats.
        /// </summary>
        public static string ItemSubcategories_Hats {
            get {
                return ResourceManager.GetString("ItemSubcategories_Hats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helmets.
        /// </summary>
        public static string ItemSubcategories_Helmets {
            get {
                return ResourceManager.GetString("ItemSubcategories_Helmets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holsters.
        /// </summary>
        public static string ItemSubcategories_Holsters {
            get {
                return ResourceManager.GetString("ItemSubcategories_Holsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illumination.
        /// </summary>
        public static string ItemSubcategories_Illumination {
            get {
                return ResourceManager.GetString("ItemSubcategories_Illumination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Sources.
        /// </summary>
        public static string ItemSubcategories_LightSources {
            get {
                return ResourceManager.GetString("ItemSubcategories_LightSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masks.
        /// </summary>
        public static string ItemSubcategories_Masks {
            get {
                return ResourceManager.GetString("ItemSubcategories_Masks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicines.
        /// </summary>
        public static string ItemSubcategories_Medicines {
            get {
                return ResourceManager.GetString("ItemSubcategories_Medicines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Ammunition.
        /// </summary>
        public static string ItemSubcategories_MiscellaneousAmmunition {
            get {
                return ResourceManager.GetString("ItemSubcategories_MiscellaneousAmmunition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Magazines.
        /// </summary>
        public static string ItemSubcategories_MiscellaneousMagazines {
            get {
                return ResourceManager.GetString("ItemSubcategories_MiscellaneousMagazines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muzzle Attachments.
        /// </summary>
        public static string ItemSubcategories_MuzzleAttachments {
            get {
                return ResourceManager.GetString("ItemSubcategories_MuzzleAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string ItemSubcategories_Other {
            get {
                return ResourceManager.GetString("ItemSubcategories_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pants.
        /// </summary>
        public static string ItemSubcategories_Pants {
            get {
                return ResourceManager.GetString("ItemSubcategories_Pants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reanimation.
        /// </summary>
        public static string ItemSubcategories_Reanimation {
            get {
                return ResourceManager.GetString("ItemSubcategories_Reanimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Kits.
        /// </summary>
        public static string ItemSubcategories_RepairKits {
            get {
                return ResourceManager.GetString("ItemSubcategories_RepairKits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string ItemSubcategories_Resources {
            get {
                return ResourceManager.GetString("ItemSubcategories_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rifle Ammunition.
        /// </summary>
        public static string ItemSubcategories_RifleAmmunition {
            get {
                return ResourceManager.GetString("ItemSubcategories_RifleAmmunition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rifle Magazines.
        /// </summary>
        public static string ItemSubcategories_RifleMagazines {
            get {
                return ResourceManager.GetString("ItemSubcategories_RifleMagazines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rifles.
        /// </summary>
        public static string ItemSubcategories_Rifles {
            get {
                return ResourceManager.GetString("ItemSubcategories_Rifles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirts and Jackets.
        /// </summary>
        public static string ItemSubcategories_ShirtsAndJackets {
            get {
                return ResourceManager.GetString("ItemSubcategories_ShirtsAndJackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shotgun Ammunition.
        /// </summary>
        public static string ItemSubcategories_ShotgunAmmunition {
            get {
                return ResourceManager.GetString("ItemSubcategories_ShotgunAmmunition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shotguns.
        /// </summary>
        public static string ItemSubcategories_Shotguns {
            get {
                return ResourceManager.GetString("ItemSubcategories_Shotguns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sights and Optics.
        /// </summary>
        public static string ItemSubcategories_SightsAndOptics {
            get {
                return ResourceManager.GetString("ItemSubcategories_SightsAndOptics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speedloaders.
        /// </summary>
        public static string ItemSubcategories_Speedloaders {
            get {
                return ResourceManager.GetString("ItemSubcategories_Speedloaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splints.
        /// </summary>
        public static string ItemSubcategories_Splints {
            get {
                return ResourceManager.GetString("ItemSubcategories_Splints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submachinegun Magazines.
        /// </summary>
        public static string ItemSubcategories_SubMachineGunMagazines {
            get {
                return ResourceManager.GetString("ItemSubcategories_SubMachineGunMagazines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submachine Guns.
        /// </summary>
        public static string ItemSubcategories_SubmachineGuns {
            get {
                return ResourceManager.GetString("ItemSubcategories_SubmachineGuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string ItemSubcategories_Temperature {
            get {
                return ResourceManager.GetString("ItemSubcategories_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tents.
        /// </summary>
        public static string ItemSubcategories_Tents {
            get {
                return ResourceManager.GetString("ItemSubcategories_Tents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ItemSubcategories_Tools {
            get {
                return ResourceManager.GetString("ItemSubcategories_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetables.
        /// </summary>
        public static string ItemSubcategories_Vegetables {
            get {
                return ResourceManager.GetString("ItemSubcategories_Vegetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vests.
        /// </summary>
        public static string ItemSubcategories_Vests {
            get {
                return ResourceManager.GetString("ItemSubcategories_Vests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wraps.
        /// </summary>
        public static string ItemSubcategories_Wraps {
            get {
                return ResourceManager.GetString("ItemSubcategories_Wraps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Rarities_Common {
            get {
                return ResourceManager.GetString("Rarities_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string Rarities_NA {
            get {
                return ResourceManager.GetString("Rarities_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        public static string Rarities_Rare {
            get {
                return ResourceManager.GetString("Rarities_Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommon.
        /// </summary>
        public static string Rarities_Uncommon {
            get {
                return ResourceManager.GetString("Rarities_Uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Rarities_Unknown {
            get {
                return ResourceManager.GetString("Rarities_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Rare.
        /// </summary>
        public static string Rarities_VeryRare {
            get {
                return ResourceManager.GetString("Rarities_VeryRare", resourceCulture);
            }
        }
    }
}
